name: 'Readme Action'

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  jobs_1:
    name: 'Generate github statistics img'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: 'Install dependencies'
      run: |
        python3 -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: 'Generate images'
      env:
        GITHUB_ACTOR: ${{ secrets.GH_ACTOR }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        EXCLUDED: ${{ secrets.EXCLUDED }}
        EXCLUDED_LANGS: ${{ secrets.EXCLUDE_LANGS }}
        COUNT_STATS_FROM_FORKS: ${{ secrets.COUNT_STATS_FROM_FORKS }}
      run: |
        echo 'run at:' `date '+%Y-%m-%d %H:%M:%S'`
        python3 generate_images.py
    - name: 'Commit and push if changed'
      run: |
        git diff
        git config --global user.email "jelly_54@163.com"
        git config --global user.name "zhangguodong"
        git pull
        git add -A
        git commit -m "Daily: update README.md" || exit 0
        git push

